### ISSUE TITLE
Should probably mention that installation requires Git

### ISSUE THREAD

**Issue by amn** [fogleman/primitive#1]
Since Go is only mentioned as a dependency, then Git should be mentioned as well (is required for `go get` command). Otherwise you probably could get away with just telling how this is a Go application, and let people figure the rest themselves.

**Comment by donatj** [comment]
Anyone acquainted with `go get` and `github` knows it's going to use git. I mean it's kind of implied by it being on ***git***hub to begin with. I mean it'd be kind of silly for every Go project on github to note that it uses git.

You *can* technically just download the source as a zip as well:

<img width="373" alt="screen shot 2016-09-20 at 20 20 47" src="https://cloud.githubusercontent.com/assets/133747/18694462/cd45a69c-7f6f-11e6-9b85-0dd4ffee173a.png">
