### ISSUE TITLE
Tweet a pic and get a reply with the geometric version?

### ISSUE THREAD

**Issue by ianpurton** [fogleman/primitive#11]
Would be nice to tweet an image @PrimitivePic and get the image processed as a reply. Not sure if this is possible.

**Comment by MaxNoe** [comment]
Twitter API forbids automatic answering:
> The reply and mention functions are intended to make communication between users easier, and automating these processes in order to reach many users is considered an abuse of the feature.

https://support.twitter.com/articles/76915

**Comment by fogleman** [comment]
Done.

Optionally, you can request a shape type and number of shapes, e.g.

"@PrimitivePic 200 triangles!"
