### ISSUE TITLE
Multiple outputs

### ISSUE THREAD

**Issue by lolilolicon** [fogleman/primitive#15]
Right now `primitive` only writes one output file (except for saving frames 9caadaa),

For instance, if I want to save an svg and a png, I must do this:
```
primitive -n 100 -i x.jpg -o a.svg
gm convert -size 300 a.svg a.png
```
But what if `primitive` supported this,
```
primitive -n 100 -i x.jpg -o a.svg -o a.png
```
I don't know if the go flags package supports the above; if not, how about,
```
primitive -n 100 -i x.jpg a.svg a.png
```
which is probably easier to implement (but backward incompatible).

**Comment by cvley** [comment]
@lolilolicon `flag.Var` function in `flag` package support this:

```
primitive -n 100 -i x.jpg -o a.svg -o a.png
```

Here, a slice of output files is obtained like this `[a.svg a.png]`, and doing a loop of it will get what you want.
