### ISSUE TITLE
Export steps

### ISSUE THREAD

**Issue by Solido** [fogleman/primitive#17]
I'm having a great artistic time with Primitive. As a photograph myself there's a lot of reinterpretations of my previous works that are now accessible. So thank you for such a tool with massive palette of expressivity.

Currently the tool mix a lot of steps together. Reading the file, analysing the content, finding the best solution to match the forms, drawing them and writing the file.

Would it be possible to have an option to export the drawing steps in a basic file (Json ?) so we can draw the result in another tool (for people not confortable with Go) or have a handle in the Api so we can add other treatment to the form before it is drawn (for Gopher).

Thank you Michael for any feedback on the idea.

**Comment by fogleman** [comment]
Is the SVG export insufficient for this?

**Comment by Solido** [comment]
Obvious now you point at it ! I'll find an SVG library and see how I can extend my artistic creations based on this. Having spend my afternoon on your library it's now part of my process. Thanks !

**Comment by devindi** [comment]
@Solido check it out #26
