### ISSUE TITLE
Other potential mode

### ISSUE THREAD

**Issue by bmaltais** [fogleman/primitive#20]
Very interesting what you have done.

I was wondering if the following mode would not provide even better fit quicker:

```
bestscore = 1
for each mode (triangle, rectangle, etc, etc)
  get newscore
  if newscore is < bestscore then keep output
end
return best shape
```

This way you would get a blend of shapes that provide the quickest score decrease based on the best shape for the iteration.

Trying to understand the source code so I could try to implement. This could become a new -m option for "optimized blend mode"

**Comment by fogleman** [comment]
This is basically what combo mode does already.

**Comment by bmaltais** [comment]
OK. Reading the code I tought it was just picking one at random:

`return model.RandomState(buffer, ShapeType(rnd.Intn(5)+1), a, rnd)`

I interpreted this as a single pass based on a random pick of one of the possible mode... not cycling exhaustively through each to find the best fit for the iteration.

I am not seeing the for loop across all possible mode for that option. I might be reading the code wrong.
