### ISSUE TITLE
Can I perform transforming black-n-white image to nonoverlapping triangles?

### ISSUE THREAD

**Issue by limonte** [fogleman/primitive#27]
I'm wondering if I could transform black-n-white images to nonoverlapping triangles like this by using your library:

<img src="http://www.odditycentral.com/wp-content/uploads/2013/02/Josh-Bryan-Triangulations4-550x524.jpg" width="300">

I'm pretty sure that answer is "No", but it's worth to ask :) Maybe you know some other tool which can perform what I'm asking for?

Thanks a million! You're the badass, I'm totally amazed by PrimitivePic :rocket:

**Comment by fogleman** [comment]
No, that's very different.
