### ISSUE TITLE
SVG Output?

### ISSUE THREAD

**Issue by donatj** [fogleman/primitive#3]
It would be wonderfully awesome if you supported either SVG or some other vector form of output ;)

**Comment by globalcitizen** [comment]
+1 ... I was going to write an SVG to [LÖVE](http://love2d.org/) (Lua) converter specifically to make use of this project's output.

**Comment by fogleman** [comment]
I plan on adding SVG very soon.

**Comment by fogleman** [comment]
SVG support added. Just use a ".svg" extension for your output filename.

**Comment by donatj** [comment]
That was so fast. You are a hero.

**Comment by globalcitizen** [comment]
OK, I fulfilled my promise and wrote my tool. See https://github.com/globalcitizen/svg2love ... I noticed a few things and will open another issue.
