### ISSUE TITLE
input image

### ISSUE THREAD

**Issue by hanin1** [fogleman/primitive#32]
Where do I input My images ? 

![capture](https://cloud.githubusercontent.com/assets/16138423/18920577/b87cd20a-8599-11e6-8659-a2ca68bb6bc7.PNG)

**Comment by bmaltais** [comment]
Is kal.png in your current directory?

**Comment by hanin1** [comment]
I did not know where I put kal.pmg im my current directory .

**Comment by bmaltais** [comment]
make sure to run primitive from the folder where the image is in. If not then provide the full path to the image. For example:

primitive -i /tmp/somepicfolder/kal.png -o ...
