### ISSUE TITLE
Windows 10 primitive command not recognized

### ISSUE THREAD

**Issue by netschki** [fogleman/primitive#34]
Hi, 
first of all i'm new to go :) 
The steps i did:
1. Install go from golang.org (Installdir C:\Go)
2. Path Variable added: C:\Go\bin
3. GOROOT = C:\Go\
4. Created new workingdirectory C:\Go\workspace
5. GOPATH= C:\Go\workspace
6. then i run go get -u github.com/fogleman/primitive which runs through smooth 
After that i tried running primitive but it isn't recognized as a command, i tried powershell and command line.
What did i miss?

**Comment by wileycreativeservices** [comment]
Hi netschki,

I was in exactly the same situation, but managed to figure it out.

In your working directory, after pulling the repository, you should see some folders (bin, pkg and src) - inside 'bin' there should be the compiled 'primitive.exe'.

You might be able to add this to your shell paths, but I just run the script from within that directory (i even copy the images into the same directory before processing them).

I created a batch command that allows you to drag an image (from within the same directory as 'primitive.exe') onto the .bat file that will create a small mix of images.


[mix.txt](https://github.com/fogleman/primitive/files/508068/mix.txt)

- Put this in the same directory as 'primitive.exe'
- Have a look at the code and rename the extension to .bat
- then drag an image **from within the same directory** onto the .bat
- it should spit out a small range of images named appropriately
