### ISSUE TITLE
rgba.RGBAAt undefined (type *image.RGBA has no field or method RGBAAt)

### ISSUE THREAD

**Issue by globalcitizen** [fogleman/primitive#4]
When running the recommended install command or `go build` afterwards, I get...

```
# github.com/fogleman/primitive/primitive
primitive/util.go:145: rgba.RGBAAt undefined (type *image.RGBA has no field or method RGBAAt)
```

**Comment by fogleman** [comment]
Make sure you are using a recent Go version.

**Comment by globalcitizen** [comment]
Hrrm yep, that seems to be it. Looks like `go` is now at 1.7x and mine is 1.3x...

`go version go1.3 darwin/amd64`

My `brew` is busted as my `install_name_tool` is busted as something overwrote it, so can't upgrade that way. Trying to grab a binary package instead.
