### ISSUE TITLE
Example pictures have all rights reserved?

### ISSUE THREAD

**Issue by trimailov** [fogleman/primitive#40]
### Examples
One example from `README.md`: [link](https://camo.githubusercontent.com/caa806e8ba4c061526d87d89d334525c58c0b7af/68747470733a2f2f7777772e6d69636861656c666f676c656d616e2e636f6d2f7374617469632f7072696d69746976652f6578616d706c65732f32393136373638333230312e706e67)

Using google's reverse image search I've found which looks like original picture from flickr (as stated in the `README.md` - originals are from flickr): [flickr_link](https://www.flickr.com/photos/imageclear/29167683201)

There are more:

From `README.md`: [link](https://camo.githubusercontent.com/9d66de79a89fbd5e9fa61e30ddc7b9de4b1bb85f/68747470733a2f2f7777772e6d69636861656c666f676c656d616e2e636f6d2f7374617469632f7072696d69746976652f6578616d706c65732f32363537343238363232312e3230302e3132382e342e312e706e67)
From flickr.com: [flickr_link](https://www.flickr.com/photos/64725727@N06/26574286221)

I have not searched more. 

### Problem

Both examples have `All rights reserved` for license. 

In photography (or any other creative activity) just as in software programming, there are licenses which must be respected even if you can break them easily (how can let flickr download images with all rights reserved this easily - is another topic and mystery to me).

As an amateur photographer I have seen this a few times. People from different industries forget that other creative work is under some license as well and it's not always allowed to modify or share work without attribution or informing the original author.

### Confusion

@fogleman, maybe you've asked for permission from authors to use these photos? Maybe there are originals somewhere, which are under public domain or creative commons? Or maybe google found some stolen content? Then I am sorry for my confusion. 

### Solutions

@fogleman - you have a very nice collection of open source software projects, where some of them I am following and/or using, though if the problem is true, probably the best solution would be to find other pictures on flickr which are allowed to be modified[0] (their search allows to filter by license) and use them as examples. Also, not forget to mention the original author and the original picture. It would be just very good practice to do so even if license does not enforces this. Example section would be much nicer as well, as we could compare original images with transformed ones.

#### macOS app

I have not done reverse search, but are all images in [https://primitive.lol/](https://primitive.lol/) have licenses for sharing modified work?
 
[0] This is important - not all CC images are allowed to be modified.

**Comment by fogleman** [comment]
I got permission for photos used in their original form:

![screen shot 2016-11-16 at 7 51 47 am](https://cloud.githubusercontent.com/assets/520208/20348023/9e21cac4-abd1-11e6-8fe8-3c2ddd23b6d7.png)

I think an argument could be made regarding the other images. If I look at a picture and draw it, is that okay? That's essentially what the algorithm is doing. Sometimes it becomes recognizable, but I'm not sure I would call it a "modification".

The twitter bot does link to the originals, btw.

**Comment by trimailov** [comment]
If you got the permission then it's a non-issue. :)

>I think an argument could be made regarding the other images. If I look at a picture and draw it, is that okay? That's essentially what the algorithm is doing. Sometimes it becomes recognizable, but I'm not sure I would call it a "modification".

Probably depends on how you look at this. In one way software creates new image using the original as an example. On the other hand, if you look at the result picture it looks like a modification of the original, like some kind of 'geometric shape' or 'thick artistic brush' filter.
