### ISSUE TITLE
Mac app

### ISSUE THREAD

**Issue by TGWC** [fogleman/primitive#48]
hi,

It's possible to create a Mac app that runs a go script ? How? Thanks a lot

**Comment by fogleman** [comment]
A couple of options:

1. Build a regular Go binary, launch it via NSTask and communicate over stdin/stdout. https://developer.apple.com/reference/foundation/nstask

2. Build a shared or static library and link to it. http://blog.ralch.com/tutorial/golang-sharing-libraries/
