### ISSUE TITLE
Link back to original Flickr images in README?

### ISSUE THREAD

**Issue by KixPanganiban** [fogleman/primitive#6]
Hi, it would probably be cool if you would link back to the original Flickr images so that

1. We can see the input images
1. The artists get proper credit!

Edit add: and on the Twitter account as well :)

(Or maybe add an optional text watermark with those details?)

**Comment by migueldemoura** [comment]
Cooking a pull request with this. Only a small change is required in the bot's main.py

**Comment by fogleman** [comment]
Fixed.
