### ISSUE TITLE
Telegram bot?

### ISSUE THREAD

**Issue by Salvatore-Giordano** [fogleman/primitive#64]
@fogleman, are you ok if I make a telegram bot that modify user pictures and send them back?
I'm already crafting it, but if you don't agree I'll stop.

**Comment by fogleman** [comment]
Go for it.

**Comment by Salvatore-Giordano** [comment]
Done. Just search on telegram for @PrimitivePics_Bot!
It's not really performant but it works and I'll improve it somehow 👍
