### ISSUE TITLE
Silently fails when specifying jpg as output

### ISSUE THREAD

**Issue by awestroke** [fogleman/primitive#7]
Running latest Go on Windows 10, specifying
```
primitive.exe -i file.jpg -o otherfile.jpg -n 100 -v
```
fails to write the output file with no error, verbose output ends with `writing otherfile.jpg`.
Switching to `-o otherfile.png` works.

**Comment by awestroke** [comment]
I see that jpg is not listed in the output formats section in the README, but even so, the program should crash when specifying an unsupported output format

**Comment by pravj** [comment]
I get the same result, running Ubuntu 14.04 and go version go1.5 linux/amd64.

**Comment by phlppk** [comment]
jpgs seem to work for me but I have the same issue with (not) writing gifs...
