### ISSUE TITLE
How can I do that?

### ISSUE THREAD

**Issue by DyeffersonAz** [fogleman/primitive#76]
![image](https://user-images.githubusercontent.com/16638560/34321933-8e6c3016-e801-11e7-9d5c-84ed21b66ac0.png)
Translation: 'primitive' is not recognized as a intern comand or an lot operable program

How can I do that?

**Comment by ccothrun** [comment]
Paths are handled differently on Windows, I found that the primitive executable was not on my path after building in Windows, it was in the c:\Users\%USERPROFILE%\go\bin folder. So I used the command c:\users\chris\go\bin\primitive -i d:\Projects\primitive\toto.png -o d:\Projects\primitive\toto_p.jpg -n 100 and it worked.
