### ISSUE TITLE
Element size based on color

### ISSUE THREAD

**Issue by rybi** [fogleman/primitive#8]
While I am not sure how to implement it, I would like to propose a new way of shape generation. 
Right now it starts with large shapes and adds smaller ones with each progression. I'd like to start with large dark shapes, and continue to medium large medium bright shapes up to small bright shapes. 
This would replicate a more traditional way of painting, and - I hope - make an interesting effect.
Is there a way to implement it in the current codebase?

**Comment by fogleman** [comment]
Interesting idea, but not really sure how it would be implemented in the current codebase.

**Comment by rybi** [comment]
I've used imagemagick to achieve something similar to what I had in mind. See the "Update" portion of the blog post: https://rybakov.com/blog/primitive/
Does not seem to be too groundbreaking however..
